services:
  nginx:
    image: nginx
    ports:
      - "80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d/
    volumes_from:
      - fpm
    links:
      - fpm
  fpm:
    build: .
    volumes:
      - /var/www/html/laravel
